apply plugin: 'com.android.library'

android {
    namespace "com.aviadl40.gdxbt.android"

    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 18
        targetSdkVersion 36
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation project(":gdxperms-core")
    implementation project(":gdxperms-android")
    api "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    implementation project(':gdxbt-core')
}
